<?php
defined('BASEPATH') or exit('No direct script access allowed');
$active_group = 'default';
$query_builder = true;

defined('DATABASE_SERVICE_NAME') OR define('DATABASE_SERVICE_NAME', $_ENV['DB_SERVICE_NAME']);

$db['default'] = array(
    'dsn' => '',
    'hostname' => '(DESCRIPTION = (ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = amecdb2)(PORT = 1521)) )(CONNECT_DATA =(SERVICE_NAME = '.DATABASE_SERVICE_NAME.')))',
    'username' => $_ENV['DB_USER'],
    'password' => $_ENV['DB_PASS'],
    'database' => $_ENV['DB_DATABASE'],
    'dbdriver' => $_ENV['DB_DRIVER'],
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);

$db['auditDB'] = array(
    'dsn' => '',
    'hostname' => $_ENV['AUD_HOST'],
    'username' => $_ENV['AUD_USER'],
    'password' => $_ENV['AUD_PASS'],
    'database' => $_ENV['AUD_NAME'],
    'dbdriver' => $_ENV['AUD_DRIVER'],
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);


$db['docinv'] = array(
    'dsn' => '',
    'hostname' => $_ENV['DOC_HOST'],
    'username' => $_ENV['DOC_USER'],
    'password' => $_ENV['DOC_PASS'],
    'database' => $_ENV['DOC_NAME'],
    'dbdriver' => $_ENV['DOC_DRIVER'],
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);

$db['scm'] = array(
    'dsn' => '',
    'hostname' => $_ENV['SCM_HOST'],
    'username' => $_ENV['SCM_USER'],
    'password' => $_ENV['SCM_PASS'],
    'database' => $_ENV['SCM_NAME'],
    'dbdriver' => $_ENV['SCM_DRIVER'],
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);

$db['pdm'] = array(
	'dsn'	=> '',
	'hostname' => $_ENV['PDM_HOST'],
    'username' => $_ENV['PDM_USER'],
    'password' => $_ENV['PDM_PASS'],
    'database' => $_ENV['PDM_NAME'],
    'dbdriver' => $_ENV['PDM_DRIVER'],
	'dbprefix' => '',
	'pconnect' => false,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => false,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => false,
	'compress' => false,
	'stricton' => false,
	'failover' => array(),
	'save_queries' => true
);

$db['escs'] = array(
    'dsn'	=> '',
    // 'hostname' => '(DESCRIPTION = (ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = amecdb2)(PORT = 1521)) )(CONNECT_DATA =(SERVICE_NAME = MITSU)))',
    'hostname' => '(DESCRIPTION = (ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = amecdb2)(PORT = 1521)) )(CONNECT_DATA =(SERVICE_NAME = '.DATABASE_SERVICE_NAME.')))',
    'username' => $_ENV['ESCS_USER'],
    'password' => $_ENV['ESCS_PASS'],
    'database' => $_ENV['ESCS_NAME'],
    'dbdriver' => $_ENV['ESCS_DRIVER'],
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true
);

$db['as400'] = array(
	'dsn'	=> '',
	'hostname' => $_ENV['AS_HOST'],
	'username' => $_ENV['AS_USER'],
	'password' => $_ENV['AS_PASS'],
	'database' => $_ENV['AS_NAME'],
	'dbdriver' => 'odbc',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['workload'] = array(
    'dsn' => '',
    'hostname' => $_ENV['WL_HOST'],
    'username' => $_ENV['WL_USER'],
    'password' => $_ENV['WL_PASS'],
    'database' => $_ENV['WL_NAME'],
    'dbdriver' => $_ENV['WL_DRIVER'],
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);

$db['training_record'] = array(
    'dsn' => '',
    'hostname' => $_ENV['TRAIN_HOST'],
    'username' => $_ENV['TRAIN_USER'],
    'password' => $_ENV['TRAIN_PASS'],
    'database' => $_ENV['TRAIN_NAME'],
    'dbdriver' => $_ENV['TRAIN_DRIVER'],
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);

